### ISSUE TITLE
Alternate method for accessing Gtalk (or the text portion of Hangouts)

### ISSUE THREAD

**Issue by packetgeek** [bentglasstube/bitlbee-gvoice#1]
I'm not sure that a separate module is needed.  I'm able to use the old XMPP option by using Google App Passwords.  An app password can be acquired by logging into Google and:

1) Open your account settings
2) Click on "Sign in & security"
3) Under "Password & sign in method", click on "App passwords".  Google will ask you to log in again.
4) Use the drop-down menu for "Select App" and select "Other (custom name)".  Enter "google talk" or something similar.
5) Click "Generate"
6) Copy the password from the yellow box and use it to log in.  Note: if it doesn't work, try removing the spaces.

I'm using the above to access Google Hangout's text chat via Bitlbee, using the old recipe for Gtalk.

Note: above allows a specific app to avoid the TFA normally required for Google logins.  Recommend keeping it safe.

**Comment by bentglasstube** [comment]
I have used bitlbee in the past to access the XMPP part of hangouts/gtalk as well.  The goal of this module was to access google voice for SMS.

**Comment by packetgeek** [comment]
Rgr.  Thanks.  Putting this one on my "to do" list.
